### ISSUE TITLE
image download issue...

### ISSUE THREAD

**Issue by gutow** [jcu-eresearch/static-plone-wget#4]
I'm not quite sure what is happening here. It may relate to the use of javascript in plone to link to the underlying full image. Here's the scenario. One of my sites has lots of images that are displayed in plone pages using one of the thumbnail sizes. On the active site, clicking on the image opens the full image. All static-plone-wget does is access the thumbnail. It is not clear how to get around this as I believe the action that gets the full image is triggered as a javascript event. Any thoughts or ideas?

**Comment by davidjb** [comment]
It'll depend on the behaviour and what clicking on the image is triggering; wget is just parsing resources out of the HTML so if it's not picking the images up, it's probably JavaScript in some fashion (eg especially if it's a gallery/lightbox or the like). 

Getting the images themselves downloaded at all is is a case of getting links to them into the HTML of your site. A way of doing this is by creating a Collection of all Images across your site (and making sure that Collection is itself linked to in the HTML so wget can find it), or else ensuring your Site Map lists the images.

This would get the images downloaded, but then you'll have to look at the behaviour of the image click handler and whether URL changes to the full images is required.  Things might "just work" (eg if the full-size image URLs are relative and filenames weren't changed by wget) but I suspect issues like the URLs remaining absolute and pointing at your domain, rather than the downloaded files.  In short, you'd look at rewriting - or somehow ensure wget rewrites - URLs to these full images wherever they're being called in the JS or HTML.

PRs are definitely welcome to improve the script if there's something wget or the post processing should be doing to make this work; or documentation if the issue is specifically tied to a specific Plone add-on or JS library.

**Comment by davidjb** [comment]
Closing out this old issue; PRs are welcome 👍

**Comment by gutow** [comment]
It is about time for me to try that backup cycle again. If I come up with a solution I will generate a PR.
